/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "krnuedjpsfnspnukzbqd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtybnVlZGpwc2Zuc3BudWt6YnFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyNzg5OTEsImV4cCI6MjA3ODg1NDk5MX0.zzuUmLA6M_u-qUm37Eodqs1OmdI4HftB-0OwT8q2WW8"